addSbtPlugin("com.typesafe.sbt"   %  "sbt-native-packager"   % "1.8.1")
addSbtPlugin("com.typesafe.sbt"   %  "sbt-site"              % "1.4.1")
addSbtPlugin("org.scalariform"    %  "sbt-scalariform"       % "1.8.3")
addSbtPlugin("org.scoverage"      %  "sbt-scoverage"         % "1.9.3")
addSbtPlugin("org.scalastyle"     %% "scalastyle-sbt-plugin" % "1.0.0")